enum class TokenType {
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, STAR, PERCENT,
    AMPERSAND, PIPE, CARET, TILDE,

    // Multi-character operators
    DOLLAR, DOLLAR_DOLLAR, STAR_STAR,
    PLUS_PLUS, MINUS_MINUS,
    EQUAL, EQUAL_EQUAL, STRICT_EQUAL,
    EXCL, EXCL_EQUAL,
    GREATER, GREATER_EQUAL, RIGHT_SHIFT,
    LESS, LESS_EQUAL, LEFT_SHIFT,

    // Logical operators
    IN, IS, AND, OR, NOT, NOT_IN, IS_NOT,

    // Compound assignments
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, 
    DOLLAR_EQUAL, DOLLAR_DOLLAR_EQUAL, PERCENT_EQUAL, STAR_STAR_EQUAL,

    // Literals 
    IDENTIFIER, STRING, NUMBER, TRUE, FALSE, NIL,


    // Keywords
    KEYWORD,

    EOF
}
